# Generated by Django 2.2.dev20181030223051 on 2018-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_client', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone_nr', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('id_company', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('producer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_purchase', models.IntegerField(null=True)),
                ('id_product', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('purchase_value', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_report', models.IntegerField(null=True)),
                ('id_invoice', models.IntegerField(null=True)),
                ('data_wygenerowania', models.DateField(null=True)),
            ],
        ),
    ]
